google:
  client:
    clientId: ${GOOGLE_CLIENT_ID:521675454867-pmot5ink84bf4876advcmr16o0mgg8lk.apps.googleusercontent.com}
    clientSecret: ${GOOGLE_CLIENT_SECRET:bH3wvAogUIln12u-TR-E7IEV}
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    tokenInfoUri:
    preferTokenInfo: true

admin:
  emails:
      victor.shcherb@gmail.com, dmpr0.ua@gmail.com, alex.crimean@gmail.com, stetsenko.pavlo@gmail.com

logging:
  file: logs/server.log
  config: classpath:logback-spring.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"


---

logging:
  file: /var/log/osmand-server-logs/error.log
  config: classpath:logback-spring.xml

server:
  port: 8090
  tomcat:
    accesslog:
      directory: /var/log/osmand-server-logs/
      enabled: true
      rotate: true
      pattern: '%h %l %u %t "%r" %s %b %D "%{Referer}i" "%{User-Agent}i"'

spring:
  profiles: production
